  
name: GitHub Actions Deploy WebSite

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
              node-version: 14.15
              
      - name: Install angular CLI 
        working-directory: ./connaissances-abyssales
        run: npm install -g @angular/cli
          
      - name: npm dependencies
        working-directory: ./connaissances-abyssales
        run: npm install 
         
      # Runs a set of commands using the runners shell
      - name: Build
        working-directory: ./connaissances-abyssales
        run: ng build --output-path ../docs --base-href
 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
          clean: true
